version: '3.9'
x-postgres_common: &postgres_common
  image: bitnami/postgresql:16.1.0
  restart: always
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 2s
    timeout: 2s
    retries: 5
  networks:
    - dialogue-app-network

services:
  pg_dialogue:
    <<: *postgres_common
    ports:
      - "55432:5432"
    volumes:
      - ./db/postgres/init_scripts:/docker-entrypoint-initdb.d
      - ./db/postgres/pg_dialogue_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=spacedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password

  dialogue_app:
    image: saas-dialogue-app:latest
    ports:
      - "9797:9797"
      - "7777:7777"
    depends_on:
      pg_dialogue:
        condition: service_healthy
    environment:
      - JDBC_URL=jdbc:postgresql://pg_dialogue/dialoguedb
      - R2DBC_URL=r2dbc:postgres://pg_dialogue/dialoguedb
      - PG_USERNAME=postgres
      - PG_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - space-app-network
      - dialogue-app-network

networks:
  space-app-network:
    driver: bridge
  dialogue-app-network:
    driver: bridge

volumes:
  pg_dialogue_data:
